# Test diversi spessori del radiatore

# Primo test: 0.05 mm
/detector/radiatorThickness 0.5 mm
/run/reinitializeGeometry
/run/beamOn 100

# Secondo test: 0.1 mm
/detector/radiatorThickness 1 mm
/run/reinitializeGeometry
/run/beamOn 100

# Terzo test: 0.5 mm
/detector/radiatorThickness 5 mm
/run/reinitializeGeometry
/run/beamOn 100

# Quarto test: 1 mm
/detector/radiatorThickness 10 mm
/run/reinitializeGeometry
/run/beamOn 100