############################
# --- VISUALISATION SETUP ---
############################
/vis/open OGL
/vis/viewer/set/viewpointVector 1 1 1
/vis/drawVolume
/vis/viewer/set/autoRefresh true
/vis/scene/add/trajectories smooth
/vis/scene/add/scale 1 cm
/vis/scene/add/axes
/vis/scene/add/eventID
/vis/scene/endOfEventAction accumulate

############################
# --- GPS PARTICLE SOURCE ---
############################

/gps/particle proton
/gps/energy 8 GeV

# Start position
/gps/pos/type Point
/gps/pos/centre 0 0 0 mm   # start upstream, safer than 0 0 0
/gps/pos/shape Circle
/gps/pos/radius 10 mm
/gps/pos/sigma_x 6 mm
/gps/pos/sigma_y 6 mm

# Beam direction
/gps/direction 0 0 1

# One particle per event
/gps/number 1