############################
# --- VISUALISATION SETUP ---
############################
/vis/open OGL
/vis/viewer/set/viewpointVector 1 1 1
/vis/drawVolume
/vis/viewer/set/autoRefresh true
/vis/scene/add/trajectories smooth
/vis/scene/add/scale 1 cm
/vis/scene/add/axes
/vis/scene/add/eventID
/vis/scene/endOfEventAction accumulate

############################
# --- PARTICLE GUN ---
############################
/gun/particle proton
/gun/momentumAmp 8 GeV
/gun/position 0 0 0 m
/gun/direction 0 0 1